# Generated by Django 3.2.7 on 2021-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
                ('EntryDate', models.DateField()),
                ('Direction', models.CharField(max_length=10)),
                ('EntryPrice', models.CharField(max_length=10)),
                ('StopLoss', models.CharField(max_length=10)),
                ('ProfitTarget', models.CharField(max_length=10)),
                ('ExitDate', models.DateField()),
            ],
        ),
    ]
